name: Google Cloud Function Deploy

on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deployFunction:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - id: auth
        uses: google-github-actions/auth@v0
        with:
          service_account: 'github@my-project-1548075060803.iam.gserviceaccount.com'
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - id: 'deploy'
        uses: 'google-github-actions/deploy-cloud-functions@v0'
        with:
          name: 'my-function'
          runtime: 'nodejs16'
          entry_point: 'processWebhook'
          region: 'eu-north1'
          max_instances: 1
      # Example of using the output
      - id: 'test'
        run: 'curl "${{ steps.deploy.outputs.url }}"'
